# .github/workflows/frontend.yml 6차

name: React Docker Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-react:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Build & Push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.sha }}

      - name: EC2에서 Docker 컨테이너 실행 (SSH 접속)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 기존 컨테이너가 있으면 중지 및 삭제
            docker stop react-frontend || true
            docker rm react-frontend || true
            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.sha }}
            # Docker 컨테이너 실행 (80번 포트에서 React 앱 서빙)
            docker run -d --name react-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:${{ github.sha }}
